# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

34.125.37.244	FALSE	/	FALSE	1621783848	sid	0eb87ba2c9a74d6888160adbce06e4c5dd25d71262c9e670ffccd446
34.125.37.244	FALSE	/	FALSE	0	system_user	yes
34.125.37.244	FALSE	/	FALSE	0	full_name	Alan%20Padiernos
34.125.37.244	FALSE	/	FALSE	0	user_id	alan%40abakadastudios.com
34.125.37.244	FALSE	/	FALSE	0	user_image	
